# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# import tkinter as tk

class FloorPlanMonitor:
    def __init__(self, root):
        self.root = root
        self.root.title("Floor Plan Monitor")

        # Create and pack labels for each room
        self.create_room("Exterior", "Solar Panels on the Roof")
        self.create_room("Living Room", "LED Lighting powered by Cat5", "Smart TV connected via Cat5", "Smart Thermostat controlled by Cat5")

        # Repeat similar structures for other rooms

    def create_room(self, title, *details):
        room_frame = tk.Frame(self.root, bd=2, relief=tk.GROOVE)
        room_frame.pack(padx=10, pady=10, fill=tk.X)

        title_label = tk.Label(room_frame, text=title, font=("Arial", 12, "bold"))
        title_label.pack(anchor=tk.W)

        for detail in details:
            detail_label = tk.Label(room_frame, text=detail)
            detail_label.pack(anchor=tk.W, padx=20)

if __name__ == "__main__":
    root = tk.Tk()
    app = FloorPlanMonitor(root)
    root.mainloop()
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
